// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsnJuTnsar23rvmA9JjHMUhIAtJLmyapg',
    appId: '1:907373883526:android:b56e8e48853614114b6107',
    messagingSenderId: '907373883526',
    projectId: 'kliky-7f331',
    storageBucket: 'kliky-7f331.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApb6tR53m1BXp_fxiVYnkmzYfsd4gAOR4',
    appId: '1:907373883526:ios:5d89ecb34df0937a4b6107',
    messagingSenderId: '907373883526',
    projectId: 'kliky-7f331',
    storageBucket: 'kliky-7f331.appspot.com',
    androidClientId: '907373883526-uerlifn3scprp7un33okcnf1vk788dei.apps.googleusercontent.com',
    iosClientId: '907373883526-cvugo9m1m7b1vgkm8598uiek5kme570k.apps.googleusercontent.com',
    iosBundleId: 'com.example.kliky',
  );
}
